# Generated by Django 4.0.3 on 2023-11-19 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_patient_num_patient_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('symptoms', models.CharField(max_length=255)),
                ('diagnosis', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('prescription_code', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.patient')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentData',
            fields=[
                ('treatment_code', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('therapy_type', models.CharField(max_length=50)),
                ('therapy_days', models.IntegerField()),
                ('therapy_time', models.IntegerField()),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_code', models.AutoField(primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=100)),
                ('total_dosage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.IntegerField()),
                ('duration_days', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseData',
            fields=[
                ('exercise_code', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('repetitions', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exercise_type', models.CharField(max_length=50)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationData',
            fields=[
                ('record_number', models.AutoField(primary_key=True, serialize=False)),
                ('bone_mass', models.DecimalField(decimal_places=2, max_digits=10)),
                ('body_fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('muscle_strength', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cardiovascular_endurance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('agility', models.DecimalField(decimal_places=2, max_digits=5)),
                ('flexibility', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unique_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.patient')),
            ],
        ),
    ]
